// Code generated by protoc-gen-go. DO NOT EDIT.
// source: to-do-services.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Todo struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string               `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Todo) Reset()         { *m = Todo{} }
func (m *Todo) String() string { return proto.CompactTextString(m) }
func (*Todo) ProtoMessage()    {}
func (*Todo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2d0cd0864205ee3, []int{0}
}

func (m *Todo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Todo.Unmarshal(m, b)
}
func (m *Todo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Todo.Marshal(b, m, deterministic)
}
func (m *Todo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Todo.Merge(m, src)
}
func (m *Todo) XXX_Size() int {
	return xxx_messageInfo_Todo.Size(m)
}
func (m *Todo) XXX_DiscardUnknown() {
	xxx_messageInfo_Todo.DiscardUnknown(m)
}

var xxx_messageInfo_Todo proto.InternalMessageInfo

func (m *Todo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Todo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Todo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Todo) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type MakeRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Todo                 *Todo    `protobuf:"bytes,2,opt,name=todo,proto3" json:"todo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MakeRequest) Reset()         { *m = MakeRequest{} }
func (m *MakeRequest) String() string { return proto.CompactTextString(m) }
func (*MakeRequest) ProtoMessage()    {}
func (*MakeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2d0cd0864205ee3, []int{1}
}

func (m *MakeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakeRequest.Unmarshal(m, b)
}
func (m *MakeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakeRequest.Marshal(b, m, deterministic)
}
func (m *MakeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakeRequest.Merge(m, src)
}
func (m *MakeRequest) XXX_Size() int {
	return xxx_messageInfo_MakeRequest.Size(m)
}
func (m *MakeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MakeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MakeRequest proto.InternalMessageInfo

func (m *MakeRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *MakeRequest) GetTodo() *Todo {
	if m != nil {
		return m.Todo
	}
	return nil
}

type MakeResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MakeResponse) Reset()         { *m = MakeResponse{} }
func (m *MakeResponse) String() string { return proto.CompactTextString(m) }
func (*MakeResponse) ProtoMessage()    {}
func (*MakeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2d0cd0864205ee3, []int{2}
}

func (m *MakeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakeResponse.Unmarshal(m, b)
}
func (m *MakeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakeResponse.Marshal(b, m, deterministic)
}
func (m *MakeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakeResponse.Merge(m, src)
}
func (m *MakeResponse) XXX_Size() int {
	return xxx_messageInfo_MakeResponse.Size(m)
}
func (m *MakeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MakeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MakeResponse proto.InternalMessageInfo

func (m *MakeResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *MakeResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Todo)(nil), "v1.Todo")
	proto.RegisterType((*MakeRequest)(nil), "v1.MakeRequest")
	proto.RegisterType((*MakeResponse)(nil), "v1.MakeResponse")
}

func init() { proto.RegisterFile("to-do-services.proto", fileDescriptor_e2d0cd0864205ee3) }

var fileDescriptor_e2d0cd0864205ee3 = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xcd, 0x4e, 0xc3, 0x30,
	0x10, 0x84, 0x95, 0x1f, 0x2a, 0xb2, 0x41, 0x50, 0x59, 0x3d, 0x44, 0x11, 0x12, 0x51, 0x4e, 0x91,
	0x50, 0x5d, 0x1a, 0x2e, 0x08, 0x89, 0x13, 0x67, 0x2e, 0xa6, 0x2f, 0x90, 0xd6, 0x4b, 0x65, 0xd1,
	0x76, 0x43, 0xbc, 0xcd, 0x33, 0xf0, 0xd8, 0x28, 0xb6, 0x42, 0x7b, 0xe8, 0xcd, 0x1e, 0xcf, 0xac,
	0xbf, 0x59, 0x98, 0x31, 0xcd, 0x35, 0xcd, 0x2d, 0x76, 0xbd, 0xd9, 0xa0, 0x95, 0x6d, 0x47, 0x4c,
	0x22, 0xec, 0x97, 0xf9, 0xc3, 0x96, 0x68, 0xbb, 0xc3, 0x85, 0x53, 0xd6, 0xc7, 0xaf, 0x05, 0x9b,
	0x3d, 0x5a, 0x6e, 0xf6, 0xad, 0x37, 0x95, 0xbf, 0x01, 0xc4, 0x2b, 0xd2, 0x24, 0x6e, 0x21, 0x34,
	0x3a, 0x0b, 0x8a, 0xa0, 0x8a, 0x54, 0x68, 0xb4, 0x98, 0xc1, 0x15, 0x1b, 0xde, 0x61, 0x16, 0x16,
	0x41, 0x95, 0x28, 0x7f, 0x11, 0x05, 0xa4, 0x1a, 0xed, 0xa6, 0x33, 0x2d, 0x1b, 0x3a, 0x64, 0x91,
	0x7b, 0x3b, 0x97, 0xc4, 0x0b, 0x24, 0xff, 0x7f, 0x64, 0x71, 0x11, 0x54, 0x69, 0x9d, 0x4b, 0x4f,
	0x21, 0x47, 0x0a, 0xb9, 0x1a, 0x1d, 0xea, 0x64, 0x2e, 0xdf, 0x20, 0xfd, 0x68, 0xbe, 0x51, 0xe1,
	0xcf, 0x11, 0x2d, 0x8b, 0x29, 0x44, 0x4d, 0x6b, 0x1c, 0x51, 0xa2, 0x86, 0xa3, 0xb8, 0x87, 0x98,
	0x49, 0x93, 0x23, 0x4a, 0xeb, 0x6b, 0xd9, 0x2f, 0xe5, 0x80, 0xae, 0x9c, 0x5a, 0x3e, 0xc1, 0x8d,
	0x8f, 0xdb, 0x96, 0x0e, 0x16, 0x2f, 0xe4, 0x7d, 0xc5, 0x70, 0xac, 0x58, 0xbf, 0x42, 0x3a, 0xe4,
	0x3f, 0xfd, 0xda, 0xc4, 0x23, 0x4c, 0xde, 0x3b, 0x6c, 0x18, 0xc5, 0xdd, 0x30, 0xfa, 0x8c, 0x25,
	0x9f, 0x9e, 0x04, 0x3f, 0x7d, 0x3d, 0x71, 0x5d, 0x9e, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x55,
	0x4e, 0xa7, 0x52, 0x7b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TodoServiceClient is the client API for TodoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TodoServiceClient interface {
	Create(ctx context.Context, in *MakeRequest, opts ...grpc.CallOption) (*MakeResponse, error)
}

type todoServiceClient struct {
	cc *grpc.ClientConn
}

func NewTodoServiceClient(cc *grpc.ClientConn) TodoServiceClient {
	return &todoServiceClient{cc}
}

func (c *todoServiceClient) Create(ctx context.Context, in *MakeRequest, opts ...grpc.CallOption) (*MakeResponse, error) {
	out := new(MakeResponse)
	err := c.cc.Invoke(ctx, "/v1.TodoService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TodoServiceServer is the server API for TodoService service.
type TodoServiceServer interface {
	Create(context.Context, *MakeRequest) (*MakeResponse, error)
}

func RegisterTodoServiceServer(s *grpc.Server, srv TodoServiceServer) {
	s.RegisterService(&_TodoService_serviceDesc, srv)
}

func _TodoService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.TodoService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).Create(ctx, req.(*MakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TodoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.TodoService",
	HandlerType: (*TodoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _TodoService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "to-do-services.proto",
}
